services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=ratemycourses.settings_local
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-local-development-key-change-in-production
      - POSTGRES_DB=ratemycourses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - MAILGUN_API_KEY=
      - MAILGUN_DOMAIN=
      - OWNER_NAME=
      - OWNER_ADDRESS=
      - OWNER_CITY=
      - OWNER_EMAIL=
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ratemycourses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ratemycourses"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data: