# Generated by Django 5.2.6 on 2025-09-06 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=300, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'), models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=4000)),
                ('year', models.PositiveSmallIntegerField(help_text='Year you took the course (e.g. 2024)', validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)])),
                ('semester', models.CharField(choices=[('SS', 'Sommersemester'), ('WS', 'Wintersemester')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='courses_rat_course__b69755_idx'), models.Index(fields=['user'], name='courses_rat_user_id_3afe97_idx'), models.Index(fields=['year', 'semester'], name='courses_rat_year_86ba69_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'user', 'year', 'semester'), name='uniq_user_course_term'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_1_5')],
            },
        ),
    ]