# Generated by Django 5.2.6 on 2025-09-13 12:43

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='weights_between_0_100',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practical_theoretical_preference',
            field=models.PositiveSmallIntegerField(default=50, help_text="User's preference on theory-practical spectrum (0=Very Theoretical, 100=Very Practical)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('assessment_fairness_weight__gte', 0), ('assessment_fairness_weight__lte', 100), ('difficulty_weight__gte', 0), ('difficulty_weight__lte', 100), ('learning_gain_weight__gte', 0), ('learning_gain_weight__lte', 100), ('materials_weight__gte', 0), ('materials_weight__lte', 100), ('organization_weight__gte', 0), ('organization_weight__lte', 100), ('practical_theoretical_preference__gte', 0), ('practical_theoretical_preference__lte', 100), ('practical_theoretical_weight__gte', 0), ('practical_theoretical_weight__lte', 100), ('relevance_weight__gte', 0), ('relevance_weight__lte', 100), ('support_weight__gte', 0), ('support_weight__lte', 100), ('teaching_quality_weight__gte', 0), ('teaching_quality_weight__lte', 100), ('workload_weight__gte', 0), ('workload_weight__lte', 100)), name='weights_and_preference_between_0_100'),
        ),
    ]
