# Generated by Django 5.2.6 on 2025-09-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_ratingflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Disable this rating from being displayed'),
        ),
    ]
