# Generated by Django 5.2.6 on 2025-09-13 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rating_is_disabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ratingflag',
            name='courses_rat_status_e80574_idx',
        ),
        migrations.RemoveField(
            model_name='ratingflag',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='ratingflag',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='ratingflag',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='ratingflag',
            name='status',
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['-created_at'], name='courses_rat_created_ca3db5_idx'),
        ),
    ]
