# Generated by Django 5.2.6 on 2025-09-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_ratingflag_courses_rat_status_e80574_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fachgebiet',
            field=models.CharField(blank=True, help_text='Subject area or field of study (e.g., Algorithms, Statistics)', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty or department (e.g., Computer Science, Mathematics)', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, help_text='Professor or instructor name', max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['faculty'], name='courses_cou_faculty_785e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['fachgebiet'], name='courses_cou_fachgeb_93f9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['professor'], name='courses_cou_profess_51d366_idx'),
        ),
    ]
