# Generated by Django 5.2.6 on 2025-09-13 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_fachgebiet_course_faculty_course_professor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text="Visitor's IP address")),
                ('user_agent', models.TextField(blank=True, help_text="Visitor's user agent string")),
                ('referer', models.URLField(blank=True, help_text='Referring URL', null=True)),
                ('path', models.CharField(help_text='Page path visited', max_length=500)),
                ('query_string', models.CharField(blank=True, help_text='URL query parameters', max_length=1000)),
                ('method', models.CharField(default='GET', help_text='HTTP method', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=200, help_text='HTTP response status code')),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='institut',
            field=models.CharField(blank=True, help_text='Institute or research group (e.g., Institute for Software Engineering)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institut'], name='courses_cou_institu_728020_idx'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Logged in user (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['-created_at'], name='courses_vis_created_67a7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['ip_address'], name='courses_vis_ip_addr_6f7d77_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['path'], name='courses_vis_path_6538fe_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['user'], name='courses_vis_user_id_e8914f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['created_at', 'ip_address'], name='courses_vis_created_84aa19_idx'),
        ),
    ]
