# Generated by Django 5.2.6 on 2025-09-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_visitor_course_institut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text="Short code for the faculty (e.g., 'CS', 'MATH')", max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short code for the institute', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the institute')),
            ],
            options={
                'ordering': ['faculty__name', 'name'],
            },
        ),
        # Add new foreign key fields first
        migrations.AddField(
            model_name='course',
            name='faculty_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_new', to='courses.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='institute_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_new', to='courses.institute'),
        ),
        migrations.AddField(
            model_name='institute',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='courses.faculty'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institute_new'], name='courses_cou_institu_195b1d_idx'),
        ),
    ]
