# Generated by Django 5.2.6 on 2025-09-13 15:49

from django.db import migrations


def migrate_faculty_institute_data(apps, schema_editor):
    """Migrate existing faculty and institute data from CharField to ForeignKey"""
    Course = apps.get_model('courses', 'Course')
    Faculty = apps.get_model('courses', 'Faculty')
    Institute = apps.get_model('courses', 'Institute')
    
    # Create default faculty for courses with faculty data
    faculty_map = {}
    institute_map = {}
    
    # Process all courses
    for course in Course.objects.all():
        # Handle faculty migration
        if hasattr(course, 'faculty_old') and course.faculty_old and course.faculty_old.strip():
            faculty_name = course.faculty_old.strip()
            if faculty_name not in faculty_map:
                # Create faculty if it doesn't exist
                faculty, created = Faculty.objects.get_or_create(
                    name=faculty_name,
                    defaults={
                        'code': faculty_name[:10].upper().replace(' ', ''),
                        'description': f'Migrated faculty: {faculty_name}'
                    }
                )
                faculty_map[faculty_name] = faculty
            course.faculty = faculty_map[faculty_name]
        
        # Handle institute migration
        if hasattr(course, 'institut_old') and course.institut_old and course.institut_old.strip():
            institute_name = course.institut_old.strip()
            if institute_name not in institute_map:
                # Create institute if it doesn't exist
                # Try to find a matching faculty, or create a default one
                faculty = course.faculty if course.faculty else None
                if not faculty and course.faculty_old and course.faculty_old.strip():
                    faculty_name = course.faculty_old.strip()
                    faculty = faculty_map.get(faculty_name)
                
                if not faculty:
                    # Create a default faculty
                    faculty, _ = Faculty.objects.get_or_create(
                        name='Unknown Faculty',
                        defaults={
                            'code': 'UNK',
                            'description': 'Default faculty for migrated institutes'
                        }
                    )
                
                institute, created = Institute.objects.get_or_create(
                    name=institute_name,
                    defaults={
                        'faculty': faculty,
                        'code': institute_name[:20].upper().replace(' ', ''),
                        'description': f'Migrated institute: {institute_name}'
                    }
                )
                institute_map[institute_name] = institute
            course.institute = institute_map[institute_name]
        
        course.save()


def reverse_migrate_faculty_institute_data(apps, schema_editor):
    """Reverse migration - copy data back to CharField"""
    Course = apps.get_model('courses', 'Course')
    
    for course in Course.objects.all():
        if course.faculty:
            course.faculty_old = course.faculty.name
        if course.institute:
            course.institut_old = course.institute.name
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_faculty_institute_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_faculty_institute_data,
            reverse_migrate_faculty_institute_data
        ),
    ]
