# Generated by Django 5.2.6 on 2025-09-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_complete_faculty_institute_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fachgebiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject area name (e.g., Algorithms, Statistics)', max_length=255, unique=True)),
                ('professor', models.CharField(help_text='Professor or instructor name', max_length=255)),
                ('code', models.CharField(help_text='Short code for the subject area', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the subject area')),
            ],
            options={
                'verbose_name_plural': 'Fachgebiete',
                'ordering': ['institute__faculty__name', 'institute__name', 'name'],
            },
        ),
        # Remove old indexes if they exist
        migrations.RunSQL(
            "DROP INDEX IF EXISTS courses_cou_profess_51d366_idx;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS courses_cou_institu_195b1d_idx;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.institute'),
        ),
        migrations.AddField(
            model_name='fachgebiet',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fachgebiete', to='courses.institute'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fachgebiet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.fachgebiet'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institute'], name='courses_cou_institu_195b1d_idx'),
        ),
    ]
