# Generated by Django 5.2.6 on 2025-09-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_fachgebiet_and_more'),
    ]

    operations = [
        # Remove old indexes if they exist
        migrations.RunSQL(
            "DROP INDEX IF EXISTS courses_cou_profess_51d366_idx;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS courses_cou_institu_195b1d_idx;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RemoveField(
            model_name='fachgebiet',
            name='code',
        ),
    ]
